version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marilandense
    ports:
      - 5432:5432
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/marilandense
      JWT_AUTH_KEY: 7524G98DSAY21BBUI78SART78F1VERFHW8Y8FHSD8HF23H9F09HE90HF98
  